language: php

php:
    - 7.2

install:
    - composer self-update
    - composer install

script:
    - ./vendor/bin/phpunit;
    - ./vendor/bin/phpspec run --no-interaction;
    - ./vendor/bin/behat;
