language: php

php:
    - 7.2

install:
    - composer self-update
    - composer install

script:
    - ./vendor/bin/phpunit --config tests/phpunit/phpunit.xml;
    - ./vendor/bin/phpspec run --config tests/phpspec/phpspec.yml --no-interaction;
    - ./vendor/bin/behat --config tests/behat/behat.yml;

after_script:
    - php vendor/bin/coveralls -v
